import { Product, Sale, Category } from '../types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Shirt',
    category: 'Shirts',
    price: 3,
    image: '/img.JPG',
    stock: 500,
  },
  {
    id: '2',
    name: 'Shirt',
    category: 'Shirts',
    price: 4,
    image: '/img.JPG',
    stock: 500,
  },
  {
    id: '3',
    name: 'Shirt',
    category: 'Shirts',
    price: 5,
    image: '/img.JPG',
    stock: 500,
  },
  {
    id: '4',
    name: 'Shirt',
    category: 'Shirts',
    price: 6,
    image: '/shirt_6.jpg',
    stock: 500,
  },
  {
    id: '5',
    name: 'Shirt',
    category: 'Shirts',
    price: 7,
    image: '/shirt_7.jpg',
    stock: 500,
  },
  {
    id: '6',
    name: 'Shirt',
    category: 'Shirts',
    price: 8,
    image: '/shirt_8.jpg',
    stock: 500,
  },
  {
    id: '7',
    name: 'Shirt',
    category: 'Shirts',
    price: 9,
    image: '/shirt_9.jpg',
    stock: 500,
  },
  {
    id: '8',
    name: 'Shirt',
    category: 'Shirts',
    price: 10,
    image: '/shirt_10.jpg',
    stock: 500,
  },
  {
    id: '9',
    name: 'Shirt',
    category: 'Shirts',
    price: 11,
    image: '/shirt_11.jpg',
    stock: 500,
  },
  {
    id: '10',
    name: 'Shirt',
    category: 'Shirts',
    price: 12,
    image: '/shirt_12.jpg',
    stock: 500,
  },
  {
    id: '11',
    name: 'Shirt',
    category: 'Shirts',
    price: 13,
    image: '/img.JPG',
    stock: 500,
  },
  {
    id: '12',
    name: 'Shirt',
    category: 'Shirts',
    price: 14,
    image: '/shirt_14.jpg',
    stock: 500,
  },
  {
    id: '13',
    name: 'Shirt',
    category: 'Shirts',
    price: 15,
    image: '/shirt_15.jpg',
    stock: 500,
  },
  {
    id: '14',
    name: 'Shirt',
    category: 'Shirts',
    price: 16,
    image: '/shirt_16.jpg',
    stock: 500,
  },
  {
    id: '15',
    name: 'Jeans',
    category: 'Jeans',
    price: 10,
    image: '/jean_10.jpg',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '16',
    name: 'Jeans',
    category: 'Jeans',
    price: 11,
    image: '/jean_10.jpg',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '17',
    name: 'Jeans',
    category: 'Jeans',
    price: 12,
    image: '/jean_12.jpg',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '18',
    name: 'Jeans',
    category: 'Jeans',
    price: 13,
    image: '/jean_13.jpg',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '19',
    name: 'Jeans',
    category: 'Jeans',
    price: 14,
    image: '/jean_14.jpg',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '20',
    name: 'Jeans',
    category: 'Jeans',
    price: 15,
    image: '/jean_15.jpg',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '21',
    name: 'Jeans',
    category: 'Jeans',
    price: 16,
    image: '/jean_16.jpg',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '22',
    name: 'Sets',
    category: 'Sets',
    price: 12,
    image: '/set_12.jpg',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '23',
    name: 'Sets',
    category: 'Sets',
    price: 13,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '24',
    name: 'Sets',
    category: 'Sets',
    price: 14,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '25',
    name: 'Sets',
    category: 'Sets',
    price: 15,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '26',
    name: 'Sets',
    category: 'Sets',
    price: 16,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '27',
    name: 'Sets',
    category: 'Sets',
    price: 17,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '28',
    name: 'Sets',
    category: 'Sets',
    price: 18,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '29',
    name: 'Sets',
    category: 'Sets',
    price: 19,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '30',
    name: 'Sets',
    category: 'Sets',
    price: 20,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '31',
    name: 'Sets',
    category: 'Sets',
    price: 21,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '32',
    name: 'Sets',
    category: 'Sets',
    price: 22,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '33',
    name: 'Bags',
    category: 'Bags',
    price: 5,
    image: '/img.JPG',
    stock: 500,
  },
  {
    id: '34',
    name: 'Bags',
    category: 'Bags',
    price: 6,
    image: '/img.JPG',
    stock: 500,
  },
  {
    id: '35',
    name: 'Bags',
    category: 'Bags',
    price: 7,
    image: '/img.JPG',
    stock: 500,
  },
  {
    id: '36',
    name: 'Bags',
    category: 'Bags',
    price: 8,
    image: '/img.JPG',
    stock: 500,
  },
  {
    id: '37',
    name: 'Bags',
    category: 'Bags',
    price: 9,
    image: '/bag_9.jpg',
    stock: 500,
  },
  {
    id: '38',
    name: 'Bags',
    category: 'Bags',
    price: 10,
    image: '/bag_10.jpg',
    stock: 500,
  },
  {
    id: '39',
    name: 'Bags',
    category: 'Bags',
    price: 11,
    image: '/bag_11.jpg',
    stock: 500,
  },
  {
    id: '40',
    name: 'Bags',
    category: 'Bags',
    price: 12,
    image: '/bag_12.jpg',
    stock: 500,
  },
  {
    id: '41',
    name: 'Bags',
    category: 'Bags',
    price: 13,
    image: '/bag_13.jpg',
    stock: 500,
  },
  {
    id: '42',
    name: 'Bags',
    category: 'Bags',
    price: 14,
    image: '/bag_14.jpg',
    stock: 500,
  },
  {
    id: '43',
    name: 'Dresses',
    category: 'Dresses',
    price: 12,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '44',
    name: 'Dresses',
    category: 'Dresses',
    price: 13,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '45',
    name: 'Dresses',
    category: 'Dresses',
    price: 14,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '46',
    name: 'Dresses',
    category: 'Dresses',
    price: 15,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '47',
    name: 'Dresses',
    category: 'Dresses',
    price: 16,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '48',
    name: 'Pants',
    category: 'Pants',
    price: 5,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '49',
    name: 'Pants',
    category: 'Pants',
    price: 6,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '50',
    name: 'Pants',
    category: 'Pants',
    price: 7,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '51',
    name: 'Pants',
    category: 'Pants',
    price: 8,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '52',
    name: 'Pants',
    category: 'Pants',
    price: 9,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '53',
    name: 'Pants',
    category: 'Pants',
    price: 10,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '54',
    name: 'Pants',
    category: 'Pants',
    price: 11,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '55',
    name: 'Pants',
    category: 'Pants',
    price: 12,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '56',
    name: 'Pants',
    category: 'Pants',
    price: 13,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '57',
    name: 'Shoes',
    category: 'Shoes',
    price: 8,
    image: '/img.JPG',
    stock: 500,
    sizes: ['36', '37', '38', '39'],
  },
  {
    id: '58',
    name: 'Shoes',
    category: 'Shoes',
    price: 9,
    image: '/img.JPG',
    stock: 500,
    sizes: ['36', '37', '38', '39'],
  },
  {
    id: '59',
    name: 'Shoes',
    category: 'Shoes',
    price: 10,
    image: '/img.JPG',
    stock: 500,
    sizes: ['36', '37', '38', '39'],
  },
  {
    id: '60',
    name: 'Shoes',
    category: 'Shoes',
    price: 11,
    image: '/shoes_11.jpg',
    stock: 500,
    sizes: ['36', '37', '38', '39'],
  },
  {
    id: '61',
    name: 'Shoes',
    category: 'Shoes',
    price: 12,
    image: '/shoes_12.jpg',
    stock: 500,
    sizes: ['36', '37', '38', '39'],
  },
  {
    id: '62',
    name: 'Shoes',
    category: 'Shoes',
    price: 13,
    image: '/shoes_13.jpg',
    stock: 500,
    sizes: ['36', '37', '38', '39'],
  },
  {
    id: '63',
    name: 'Shoes',
    category: 'Shoes',
    price: 14,
    image: '/shoes_14.jpg',
    stock: 500,
    sizes: ['36', '37', '38', '39'],
  },
  {
    id: '64',
    name: 'Shoes',
    category: 'Shoes',
    price: 15,
    image: '/img.JPG',
    stock: 500,
    sizes: ['36', '37', '38', '39'],
  },
  {
    id: '65',
    name: 'Shoes',
    category: 'Shoes',
    price: 16,
    image: '/img.JPG',
    stock: 500,
    sizes: ['36', '37', '38', '39'],
  },
  {
    id: '66',
    name: 'Socks',
    category: 'Socks',
    price: 1.5,
    image: '/Socks.jpg',
    stock: 500,
  },
  {
    id: '67',
    name: 'Skirts',
    category: 'Skirts',
    price: 9,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '68',
    name: 'Skirts',
    category: 'Skirts',
    price: 10,
    image: '/skirt_10.jpg',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '69',
    name: 'Skirts',
    category: 'Skirts',
    price: 11,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '70',
    name: 'Skirts',
    category: 'Skirts',
    price: 12,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '71',
    name: 'Skirts',
    category: 'Skirts',
    price: 13,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '72',
    name: 'Hat',
    category: 'Hat',
    price: 6,
    image: '/img.JPG',
    stock: 500,
  },
  {
    id: '73',
    name: 'Hat',
    category: 'Hat',
    price: 7,
    image: '/hat_7.jpg',
    stock: 500,
  },
  {
    id: '74',
    name: 'Hat',
    category: 'Hat',
    price: 8,
    image: '/hat_8.jpg',
    stock: 500,
  },
  {
    id: '75',
    name: 'Hat',
    category: 'Hat',
    price: 9,
    image: '/hat_9.jpg',
    stock: 500,
  },
  {
    id: '76',
    name: 'Jackets',
    category: 'Jackets',
    price: 12,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '77',
    name: 'Jackets',
    category: 'Jackets',
    price: 13,
    image: '/jacket_13.jpg',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '78',
    name: 'Jackets',
    category: 'Jackets',
    price: 14,
    image: '/jacket_14.jpg',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '79',
    name: 'Jackets',
    category: 'Jackets',
    price: 15,
    image: '/jacket_15.jpg',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '80',
    name: 'Jackets',
    category: 'Jackets',
    price: 16,
    image: '/img.JPG',
    stock: 500,
    sizes: ['S', 'M', 'L', 'Free Size'],
  },
  {
    id: '81',
    name: 'Pajamas',
    category: 'Pajamas',
    price: 9,
    image: '/pajamas.jpg',
    stock: 500,
    sizes: ['Free Size'],
  },
  {
    id: '82',
    name: 'Pajamas',
    category: 'Pajamas',
    price: 10,
    image: '/img.JPG',
    stock: 500,
    sizes: ['Free Size'],
  },
  {
    id: '83',
    name: 'Glasses',
    category: 'Glasses',
    price: 6,
    image: '/img.JPG',
    stock: 500,
  },
  {
    id: '84',
    name: 'Belt',
    category: 'Belt',
    price: 7,
    image: '/img.JPG',
    stock: 500,
  },
  {
    id: '85',
    name: 'ប្រដាប់ខ្ទស់ចង្កេះខោ​',
    category: 'ប្រដាប់ខ្ទស់ចង្កេះខោ​',
    price: 1.5,
    image: '/img.JPG',
    stock: 500,
  },
  {
    id: '86',
    name: 'ប្រដាប់ខ្ទស់ចង្កេះខោ​',
    category: 'ប្រដាប់ខ្ទស់ចង្កេះខោ​',
    price: 3,
    image: '/img.JPG',
    stock: 500,
  },
  {
    id: '87',
    name: 'បូចង់សក់​',
    category: 'បូចង់សក់​',
    price: 5,
    image: '/img.JPG',
    stock: 500,
  },
  {
    id: '88',
    name: 'បូចង់សក់​',
    category: 'បូចង់សក់​',
    price: 6,
    image: '/img.JPG',
    stock: 500,
  },
];

export const mockSales: Sale[] = [];

export const mockCategories: Category[] = [
  { id: '1', name: 'Shirts', color: '#F59E0B', icon: '👕' },
  { id: '2', name: 'Jeans', color: '#06B6D4', icon: '👖' },
  { id: '3', name: 'Sets', color: '#10B981', icon: '🧥' },
  { id: '4', name: 'Bags', color: '#EF4444', icon: '👜' },
  { id: '5', name: 'Dresses', color: '#8B5CF6', icon: '👗' },
  { id: '6', name: 'Pants', color: '#F97316', icon: '👖' },
  { id: '7', name: 'Shoes', color: '#3B82F6', icon: '👟' },
  { id: '8', name: 'Socks', color: '#84CC16', icon: '🧦' },
  { id: '9', name: 'Skirts', color: '#EC4899', icon: '🧥' },
  { id: '10', name: 'Hat', color: '#6B7280', icon: '🧢' },
  { id: '11', name: 'Jackets', color: '#F59E0B', icon: '🧥' },
  { id: '12', name: 'Pajamas', color: '#10B981', icon: '🛌' },
  { id: '13', name: 'Bra', color: '#06B6D4', icon: '👙' },
  { id: '14', name: 'Belt', color: '#F97316', icon: '🦮' },
  { id: '15', name: 'Glasses', color: '#EF4444', icon: '🕶' },
  { id: '16', name: 'ប្រដាប់ខ្ទស់ចង្កេះខោ​', color: '#000000ff', icon: '👙' },
  { id: '17', name: 'បូចង់សក់​', color: '#adf700ff', icon: '🦮' },
];

export const banks = [
  'ABA Bank',
  'Acleda Bank',
  'Wing Bank',
  'Vattanac Bank',
  'Canadia Bank',
  'Chip Mong Bank',
  'Prince Bank',
  'FTB Bank',
];

// Exchange rate: 1 USD = 4100 KHR (approximate)
export const USD_TO_KHR_RATE = 4100;
